# Generated by Django 2.1.5 on 2019-01-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190117_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='binding',
            field=models.CharField(choices=[('Tapa blanda', 'Tapa blanda'), ('Tapa dura', 'Tapa dura')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Contemporánea', 'Contemporánea'), ('Negra', 'Negra')], max_length=50),
        ),
    ]
