# Generated by Django 2.1.5 on 2019-01-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Contemporánea', 'Contemporánea'), ('Negra', 'Negra'), ('Romántica', 'Romántica')], max_length=50),
        ),
    ]
