# Generated by Django 2.1.5 on 2019-01-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190120_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'El nombre de usuario ya existe'}, max_length=50, unique=True),
        ),
    ]
