# Generated by Django 2.1.5 on 2019-01-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190121_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='binding',
            field=models.CharField(choices=[('Tapa blanda', 'Tapa blanda'), ('Tapa dura', 'Tapa dura')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Contemporánea', 'Contemporánea'), ('Negra', 'Negra'), ('Romántica', 'Romántica'), ('Cómics', 'Cómics'), ('Historia', 'Historia'), ('Adolescentes', 'Adolescentes'), ('Infantil', 'Infantil')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='editorial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
